# chmod
[[manager.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"

# mount
[[manager.prepend_keymap]]
on  = "M"
run = "plugin mount"

# smart-enter
[[manager.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"
